# Generated by Django 2.2.4 on 2019-09-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMA_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ'), ('NASDAQ', 'NASDAQ')], default='KOSPI', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('short_ma', models.IntegerField()),
                ('long_ma', models.IntegerField()),
                ('buy_quantity', models.IntegerField()),
                ('sell_quantity', models.IntegerField()),
                ('capital_base', models.IntegerField()),
                ('shares', models.IntegerField(null=True)),
                ('last_pv', models.IntegerField(null=True)),
                ('last_value', models.IntegerField(null=True)),
                ('last_cash', models.IntegerField(null=True)),
                ('capital_used', models.IntegerField(null=True)),
                ('expected_return', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('bt_path', models.CharField(max_length=100, null=True)),
                ('pv_path', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
